# NumPy

## 导入包

In [2]:
import numpy as np

## ndarray

ndarry 是 NumPy 中重要的数据类型

## 数组创建

In [4]:
# 一维数组
value = [1,2,3] 
arr1d = np.array(value)
arr1d

array([1, 2, 3])

In [11]:
# 二维数组
value = [[1,2,3],[4,5,6]]
arr2d = np.array(value)
arr2d

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
# 全零数组
np.zeros(5)

array([ 0.,  0.,  0.,  0.,  0.])

In [13]:
# 为初始化的数组
np.empty(10)

array([  1.49166815e-154,   1.29074494e-231,   2.17992198e-314,
         2.17898232e-314,   2.53747840e-003,   0.00000000e+000,
         0.00000000e+000,  -5.18676865e+227,   2.17992873e-314,
         6.95337761e-309])

In [14]:
# 创建元素都为1的数组
np.ones(5)

array([ 1.,  1.,  1.,  1.,  1.])

In [15]:
# 数组元素从0 到 9
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
# arange() 中的参数分别是：起始值，终值（不被包含），步长（类似等差数列）
np.arange(2, 10, 2)

array([2, 4, 6, 8])

In [21]:
# 从一维数组到二维数组
mat = np.arange(1,17)
mat.shape = (4, 4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

## 查看数组类型

In [35]:
# numpy数组和列表不同，只能存放同一类型的内容
mat.dtype

dtype('int64')

## 查看数组维度

In [5]:
arr1d.ndim

1

In [9]:
arr1d.shape

(3,)

In [8]:
arr2d.ndim

2

In [10]:
arr2d.shape

(2, 3)

## 数组切片

In [17]:
arr = np.arange(10)
arr[0]

0

In [18]:
arr[3:7]

array([3, 4, 5, 6])

In [19]:
# 数组切片是原数据，改变切片，改变原值
arr2 = arr[3:7]
arr2[0] = 13
arr 

array([ 0,  1,  2, 13,  4,  5,  6,  7,  8,  9])

In [22]:
# 二维数组切片是一维数组
mat[0]

array([1, 2, 3, 4])

In [26]:
# 也可以切两层
mat[1:3]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [29]:
# 获得单个元素, 下面两个等价
mat[0][3]
mat[0, 3]

4

In [30]:
# 获得某行，某列
# 如果只有一列，则是一维数组
mat[0:3, 1]

array([ 2,  6, 10])

In [33]:
# 如果是多列，则是二维数组
mat[0:3, 1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

## 使用布尔型索引筛选

In [38]:
# 获取布尔型索引, 形成行的索引
mat[:, 0] > 10

array([False, False, False,  True], dtype=bool)

In [40]:
# 通过布尔型索引筛选出附和行索引的行
mat[mat[:, 0] > 10]

array([[13, 14, 15, 16]])

In [43]:
# 布尔索引也可以叠加
mat[(mat[:, 0] > 10) | (mat[:, 0] < 3)]

array([[ 1,  2,  3,  4],
       [13, 14, 15, 16]])

## 数组运算

NumPy数组运算会自动做扩展，称之为广播

In [44]:
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [45]:
mat / 2

array([[ 0.5,  1. ,  1.5,  2. ],
       [ 2.5,  3. ,  3.5,  4. ],
       [ 4.5,  5. ,  5.5,  6. ],
       [ 6.5,  7. ,  7.5,  8. ]])

In [46]:
mat ** 2

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144],
       [169, 196, 225, 256]])

In [47]:
mat + mat

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24],
       [26, 28, 30, 32]])

In [48]:
mat * mat

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144],
       [169, 196, 225, 256]])

In [49]:
# 对列求和
np.sum(mat, axis=0)

array([28, 32, 36, 40])

In [50]:
# 对行求和
np.sum(mat, axis=1)

array([10, 26, 42, 58])

In [51]:
# 列的平均
np.mean(mat, axis=0)

array([  7.,   8.,   9.,  10.])

In [52]:
# 列的最大值
np.max(mat, axis=0)

array([13, 14, 15, 16])

In [53]:
# 列的最小值
np.min(mat, axis=0)

array([1, 2, 3, 4])

In [55]:
# 对某一列排序
np.sort(mat[:, 0])

array([ 1,  5,  9, 13])

In [56]:
# 对某一列去重
np.sort(mat[:, 0])

array([ 1,  5,  9, 13])

In [58]:
# 使用np.where()函数，有点类似布尔索引
np.where(mat[:,0] >= 6, 'Big', 'Small')

array(['Small', 'Small', 'Big', 'Big'], 
      dtype='<U5')